version: "3.7"
services:
  ################################  thule-discovery-service  ################################
  thule-discovery-service:
    image: pooh:8084/thule-discovery-service
    environment:
      EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS: 5 # By default eureka server can take a long time to start due to the default lease renewal of 30 seconds
      JDK_JAVA_OPTIONS: -XX:InitialHeapSize=256m -XX:MaxHeapSize=256m -XX:MaxMetaspaceSize=256m
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_ZIPKIN_ENABLED: "false"
      THULE_SHARED_LOGGING_LOGSTASH_ENABLED: "false"
      TZ: Europe/London
    networks:
      - thule-discovery-service
    ports:
      - 9761:8080

################################  Networks  ################################
networks:
  thule-discovery-service:
