---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: thule-discovery-service-pod-reader
  namespace: thule
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: thule-discovery-service-role-binding
  namespace: thule
roleRef:
  kind: ClusterRole
  name: thule-discovery-service-pod-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: thule-discovery-service-account
    namespace: thule
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: thule-discovery-service
  namespace: thule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thule-discovery-service
      namespace: thule
  template:
    metadata:
      labels:
        app: thule-discovery-service
        namespace: thule
    spec:
      serviceAccountName: thule-discovery-service-account
      containers:
        - name: thule-discovery-service
          image: pooh:8082/thule-discovery-service:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: JDK_JAVA_OPTIONS
              value: -XX:InitialHeapSize=256m -XX:MaxHeapSize=256m -XX:MaxMetaspaceSize=256m
            - name: SPRING_PROFILES_ACTIVE
              value: cit
            - name: TZ
              value: Europe/London
            - name: ROLLOUT_TIME
              value:
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: service-port
            initialDelaySeconds: 300
            periodSeconds: 30
            timeoutSeconds: 10
          ports:
            - containerPort: 8080
              name: service-port
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: service-port
            periodSeconds: 30
            timeoutSeconds: 10
      hostAliases:
        - ip: 192.168.0.102
          hostnames:
            - pooh
        - ip: 192.168.0.104
          hostnames:
           - piglet.serin-consultancy.co.uk
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: thule-discovery-service-hpa
  namespace: thule
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: thule-discovery-service
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "/thule-discovery-service"
  name: thule-discovery-service-ingress
  namespace: thule
spec:
  rules:
    - host: piglet.serin-consultancy.co.uk
      http:
        paths:
          - path: /thule-discovery-service(/|$)(.*)
            backend:
              serviceName: thule-discovery-service
              servicePort: 80
  tls:
    - hosts:
       - piglet.serin-consultancy.co.uk
      secretName: thule-application-secrets
---
kind: Service
apiVersion: v1
metadata:
  name: thule-discovery-service
  namespace: thule
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: thule-discovery-service
    namespace: thule
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: thule-discovery-service-account
  namespace: thule
