# Flyway configuration
flyway:
  enabled: false

# Spring configuration
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:hsqldb:mem:testdb
  jpa:
    hibernate:
      ddl-auto: update
