# Eureka configuration
eureka:
  client:
    enabled: false
    serviceUrl:
      # Location of peer discovery services to keep the registry in sync across all discovery services, in this case we only have a single node so it refers to itself
      defaultZone: http://${thule.discoveryservice.host:localhost}:${thule.discoveryservice.port:8080}/eureka/
  instance:
    # Hostname will be the docker container hostname by default which will not will not be accessible outside of the host itself, so use ipaddress instead
    prefer-ip-address: true

# Spring actuator configuration
info:
  description: Thule Config Service
  name: ${spring.application.name}

# Spring logging
logging:
  level:
    org.springframework: info
    uk.co.serin: trace

# Spring boot configuration
spring:
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config/{application}
  sleuth:
    sampler:
      probability: 1.0

# Thule configuration
thule:
  shared:
    logging:
      logstash:
        enabled: true