# Spring actuator configuration
info:
  description: Thule Configuration Service
  name: ${spring.application.name}

# Management endpoint configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

# Spring boot configuration
spring:
  application:
    name: thule-configuration-service
  cloud:
    config:
      server:
        native:
          search-locations: ${thule.configurationservice.search-locations:/config}/{application}
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://pooh.serin-consultancy.co.uk:9411
    sender:
      type: web

# Thule configuration
thule:
  shared:
    logging:
      logstash:
        enabled: true
        host: pooh.serin-consultancy.co.uk