version: "3.5"
services:
  ################################  thule-email-server  ################################
  thule-email-service:
    image: thule-email-service
    environment:
      EUREKA_CLIENT_ENABLED: "false" # Standalone container tests do not need a discovery service
      LOGGING_LEVEL_UK_CO_SERIN: trace
      SPRING_CLOUD_CONFIG_ENABLED: "false" # Standalone container tests do not need a config server
      TZ: Europe/London
    ports:
      - 8092:8080
