# Eureka configuration
eureka:
  client:
    enabled: false

# Spring logging
logging:
  level:
    uk.co.serin.thule: trace

# Thule configuration
thule:
  shared:
    logging:
      logstash:
        enabled: false