version: "3.5"
services:
  ################################  thule-email-server  ################################
  thule-email-service:
    image: thule-email-service
    environment:
      EUREKA_CLIENT_ENABLED: "false"
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_CLOUD_CONFIG_FAILFAST: "false"
      TZ: Europe/London
    extra_hosts:
      - logstash-host:172.17.0.1
      - zipkin-host:172.17.0.1
    hostname: email-server-1
    ports:
      - 8091:8080
