-- Prevent from expiring
ALTER USER system IDENTIFIED BY system;

-- Create user
BEGIN EXECUTE IMMEDIATE 'DROP USER thule CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE USER thule PROFILE DEFAULT IDENTIFIED BY thule
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS
  QUOTA UNLIMITED ON USERS
  ACCOUNT UNLOCK;


-- Grants
GRANT CREATE SESSION
  ,SELECT_CATALOG_ROLE
  ,CREATE TYPE
  ,CREATE VIEW
  ,CREATE TABLE
  ,CREATE TRIGGER
  ,CREATE SEQUENCE
  ,CREATE SNAPSHOT
  ,CREATE PROCEDURE
  ,QUERY REWRITE
  ,CREATE ANY SYNONYM
to thule;


