version: "2"
services:
  ################################  thule-config-service  ################################
  thule-config-service:
    image: pooh.serin-consultancy.co.uk/thule-config-service
    environment:
      EUREKA_CLIENT_ENABLED: "false"
    extra_hosts:
      - logstash-host:172.17.0.1
      - zipkin-host:172.17.0.1
    hostname: config-service-1
    ports:
      - "8888:8888"
    volumes:
      # Set localtime and timezone on container to be the same as the host
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro