# Spring boot configuration
spring:
  mail:
    host: localhost
    port: 1025
  zipkin:
    enabled: false

# Thule configuration
thule:
  shared:
    logging:
      logstash:
        enabled: false
