# Spring server configuration
server:
  port: 8761

# Spring boot configuration
spring:
  zipkin:
    enabled: false

# Thule configuration
thule:
  shared:
    logging:
      logstash:
        enabled: false

