version: "3.5"
services:
  ################################  thule-admin-service  ################################
  thule-admin-service:
    image: pooh:8084/thule-admin-service
    environment:
      JDK_JAVA_OPTIONS: -XX:InitialHeapSize=256m -XX:MaxHeapSize=256m -XX:MaxMetaspaceSize=256m
      # Since we are not using the configuration service to provide spring config, we instruct spring to use the config
      # from a docker volume created at build time which contains the source for this micro-service
      SPRING_ZIPKIN_ENABLED: "false"
      THULE_SHARED_LOGGING_LOGSTASH_ENABLED: "false"
      TZ: Europe/London
    ports:
      - 9093:8080 # Required to allow docker tests to call the restful api
