version: "3.7"
services:
  ################################  thule-admin-service  ################################
  thule-admin-service:
    image: pooh:8084/thule-admin-service
    environment:
      JDK_JAVA_OPTIONS: -XX:InitialHeapSize=256m -XX:MaxHeapSize=256m -XX:MaxMetaspaceSize=256m
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_CLOUD_KUBERNETES_ENABLED: "false"
      SPRING_ZIPKIN_ENABLED: "false"
      THULE_SHARED_LOGGING_LOGSTASH_ENABLED: "false"
      TZ: Europe/London
