# Spring actuator configuration
info:
  description: Thule Test Service
  name: ${spring.application.name}

# Spring boot configuration
spring:
  application:
    name: thule-test-service

# Thule configuration
thule:
  shared:
    oauth2:
      resourceserver:
        jws:
          enabled: false