kind: Secret
apiVersion: v1
metadata:
  name: thule-keycloak-secrets
  namespace: thule
type: Opaque
data:
  thule-gateway-service-client-secret: [(${thuleGatewayServiceClientSecret})]
  thule-people-service-client-secret: [(${thulePeopleServiceClientSecret})]
