# Spring boot configuration
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    password: thule
    url: jdbc:log4jdbc:mysql://${thule.peopleservice.mysql.host:localhost}:${thule.peopleservice.mysql.port:3306}/thule
    username: thule

# Thule configuration
thule:
  peopleservice:
    api:
      host: localhost
      port: 9094
    mysql:
      port: 3306
