# Eureka configuration
eureka:
  client:
    serviceUrl:
      # Location of peer discovery services to keep the registry in sync across all discovery services, in this case we only have a single node so it refers to itself
      defaultZone: http://${thule.discoveryservice.host:thule-discovery-service}:${thule.discoveryservice.port:8080}/eureka/
  instance:
    # Hostname will be the docker container hostname by default which will not will not be accessible outside of the host itself, so use ipaddress instead
    prefer-ip-address: true

# Spring actuator configuration
info:
  description: Thule Admin Service
  name: ${spring.application.name}

# Spring logging
logging:
  level:
    uk.co.serin.thule: info
    org.springframework: info

# Management endpoint configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

# Spring boot configuration
spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    sender:
      type: web

# Thule configuration
thule:
  shared:
    logging:
      logstash:
        enabled: true