# Eureka configuration
eureka:
  client:
    enabled: true

# Spring logging
logging:
  level:
    jdbc.sqlonly: info
    uk.co.serin: trace

# Thule configuration
thule:
  peopleservice:
    mysql:
      host: mysql
  discoveryservice:
    host: thule-discovery-service

