# Eureka configuration
eureka:
  client:
    enabled: false # Most environments (test) do no need a discovery service so it is disabled by default
    serviceUrl:
      # Location of peer discovery services to keep the registry in sync across all discovery services, in this case we only have a single node so it refers to itself
      defaultZone: http://${thule.discoveryservice.host:localhost}:${thule.discoveryservice.port:8080}/eureka/
  instance:
    # Hostname will be the docker container hostname by default which will not will not be accessible outside of the host itself, so use ipaddress instead
    prefer-ip-address: true

# Spring actuator configuration
info:
  description: Thule People Service
  name: ${spring.application.name}

# Spring logging
logging:
  level:
    jdbc.audit: error
    jdbc.connection: error
    jdbc.resultset: error
    jdbc.sqlonly: error
    jdbc.sqltiming: error
    org.springframework: info
    uk.co.serin: trace

# Management endpoint configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

# Spring boot configuration
spring:
  application:
    name: thule-people-service
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    password: thule
    url: jdbc:log4jdbc:mysql://${thule.peopleservice.mysql.host:localhost}:${thule.peopleservice.mysql.port:3306}/thule?serverTimezone=Europe/London
    username: thule
  flyway:
    baseline-on-migrate: true # Allow for case where the schema exists but Flyway did not create it. ***DO NOT*** leave set to true in prod environments
    connect-retries: 120
    password: root
    url: jdbc:mysql://${thule.peopleservice.mysql.host:localhost}:${thule.peopleservice.mysql.port:3306}/mysql
    user: root
  security:
    user:
      password: user
      roles: USER,ADMIN
  sleuth:
    sampler:
      probability: 1.0

# Thule configuration
thule:
  shared:
    logging:
      logstash:
        enabled: true