# Spring logging
logging:
  level:
    jdbc.sqlonly: info
    uk.co.serin: trace

# Spring server configuration
server:
  port: 8094

# Spring boot configuration
spring:
  flyway:
    schemas: THULE

# Thule configuration
thule:
  discoveryservice:
    host: localhost
    port: 8761
  peopleservice:
    mysql:
      host: localhost
