# Eureka configuration
eureka:
  client:
    enabled: true

# Spring server configuration
server:
  port: 8094

# Spring logging
logging:
  level:
    jdbc.sqlonly: info
    uk.co.serin: trace

# Thule configuration
thule:
  discoveryservice:
    port: 8761