# Spring Security configuration
security:
  oauth2:
    client:
      access-token-uri: http://localhost:${wiremock.server.port}/oauth/token
      client-id: gohenry-test-service
      client-secret:  secret
      grant-type: client_credentials
      scope:  All
    resource:
      jwt:
        key-value: secret

# Spring Boot configuration
spring:
  application:
    name: gohenry-test-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    discovery:
      client:
        simple:
          instances:
            gohenry-test-service:
              - uri: http://localhost:8080