# Spring logging
logging:
  level:
    uk.co.serin.thule: trace

# Spring server configuration
server:
  port: 8091

# Thule configuration
thule:
  discoveryservice:
    host: localhost
    port: 8761