# Spring boot configuration
spring:
  zipkin:
    enabled: false

# Thule configuration
thule:
  gatewayservice:
    healthcheck:
      services:
        - "thule-discovery-service"
        - "thule-configuration-service"
        - "thule-admin-service"
  shared:
    logging:
      logstash:
        enabled: false
