# Spring boot configuration
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://${mock.server.ipaddress}:${mock.server.port}/auth/realms/thule-test
  zipkin:
    enabled: false

# Thule configuration
thule:
  shared:
    logging:
      logstash:
        enabled: false
    oauth2:
      resourceserver:
        jws:
          enabled: false
