# Spring logging
logging:
  level:
    uk.co.serin.thule: trace

# Spring boot configuration
spring:
  cloud:
    kubernetes:
      discovery:
        enabled: false
  zipkin:
    enabled: false

# Thule configuration
thule:
  gatewayservice:
    healthcheck:
      services:
        - "thule-discovery-service"
        - "thule-configuration-service"
        - "thule-admin-service"
  shared:
    logging:
      logstash:
        enabled: false
