# Spring boot configuration
spring:
  cloud:
    kubernetes:
      discovery:
        enabled: false
  zipkin:
    enabled: false

# Thule configuration
thule:
  shared:
    logging:
      logstash:
        enabled: false
    oauth2:
      resourceserver:
        jws:
          enabled: false
