# Spring boot configuration
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://piglet.serin-consultancy.co.uk/thule-authentication-service/auth/realms/thule
