# Eureka configuration
eureka:
  instance:
    # Hostname will be the docker generated hostname by default which will not will not be accessible outside of the host itself, so use ipaddress instead
    preferIpAddress: true
  client:
    serviceUrl:
      # Location of the discovery service to register this service
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

# Spring actuator configuration
endpoints:
  sensitive: false
info:
  description: Thule Admin Server
  name: ${spring.application.name}

# Spring logging
logging:
  level:
    org.springframework: info
    uk.co.serin: trace

# Spring server configuration
server:
  port: 8071

# Spring boot configuration
spring:
  jackson:
    serialization:
      # Admin server displays the buildTime of this service which by default will be as an
      # absolute time (i.e. a long), not particularily meaningful unless we instruct jackson to
      # serialize it as a timestamp which is a human readable form
      write_dates_as_timestamps: false
