version: "3.5"
services:
  ################################  thule-edge-server  ################################
  thule-edge-server:
    image: pooh:8082/thule-edge-server
    environment:
      EUREKA_CLIENT_ENABLED: "false"
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_CLOUD_CONFIG_FAILFAST: "false"
      TZ: Europe/London
    extra_hosts:
      - logstash-host:172.17.0.1
      - zipkin-host:172.17.0.1
    hostname: edge-server-1
    ports:
      - 8080:8080
