version: "3.5"
services:
  ################################  thule-admin-server  ################################
  thule-admin-server:
    image: pooh:8082/thule-admin-server
    environment:
      THULE_CONFIG_SERVICE_HOST: thule-config-service
      THULE_DISCOVERY_SERVICE_HOST: thule-discovery-service
      TZ: UTC
    extra_hosts:
      - logstash-host:172.17.0.1
      - zipkin-host:172.17.0.1
    hostname: admin-server-1
    ports:
      - 9071:8071

  ################################  thule-config-service  ################################
  thule-config-service:
    image: pooh:8082/thule-config-service
    environment:
      THULE_DISCOVERY_SERVICE_HOST: thule-discovery-service
      TZ: UTC
    extra_hosts:
      - logstash-host:172.17.0.1
      - zipkin-host:172.17.0.1
    hostname: config-service-1
    ports:
      - 9888:8888

  ################################  thule-discovery-service  ################################
  thule-discovery-service:
    image: pooh:8082/thule-discovery-service
    environment:
      THULE_CONFIG_SERVICE_HOST: thule-config-service
      TZ: UTC
    extra_hosts:
      - logstash-host:172.17.0.1
      - zipkin-host:172.17.0.1
    hostname: discovery-service-1
    ports:
      - 9761:8761

  ################################  thule-edge-server  ################################
  thule-edge-server:
    image: pooh:8082/thule-edge-server
    environment:
      THULE_CONFIG_SERVICE_HOST: thule-config-service
      THULE_DISCOVERY_SERVICE_HOST: thule-discovery-service
      TZ: UTC
    extra_hosts:
      - logstash-host:172.17.0.1
      - zipkin-host:172.17.0.1
    hostname: edge-server-1
    ports:
      - 9080:8080

  ################################  thule-email-server  ################################
  thule-email-service:
    image: pooh:8082/thule-email-service
    environment:
      THULE_CONFIG_SERVICE_HOST: thule-config-service
      THULE_DISCOVERY_SERVICE_HOST: thule-discovery-service
      TZ: UTC
    extra_hosts:
      - logstash-host:172.17.0.1
      - zipkin-host:172.17.0.1
    hostname: email-server-1
    ports:
      - 9091:8091

  ################################  thule-people-service  ################################
  thule-people-service:
    image: pooh:8082/thule-people-service
    environment:
      THULE_CONFIG_SERVICE_HOST: thule-config-service
      THULE_DISCOVERY_SERVICE_HOST: thule-discovery-service
      TZ: UTC
    extra_hosts:
      - logstash-host:172.17.0.1
      - zipkin-host:172.17.0.1
    hostname: people-service-1
    ports:
      - 9090:8090
