# Eureka configuration
eureka:
  instance:
    fetch-registry: false
    registerWithEureka: false # Register discovery service itself with Eureka so we have a client service available for the integration tests
    # By default eureka server can take a long time to start due to the default lease renewal of 30 seconds
    leaseRenewalIntervalInSeconds: 5

# Spring logging
logging:
  level:
    uk.co.serin.thule: trace
