# Eureka configuration
eureka:
  instance:
    # By default eureka server can take a long time to start due to the default lease renewal of 30 seconds
    leaseRenewalIntervalInSeconds: 5

# Spring logging
logging:
  level:
    uk.co.serin.thule: trace

# Thule configuration
thule:
  shared:
    logging:
      logstash:
        enabled: false
