# Eureka configuration
eureka:
  client:
    enabled: false

# Spring logging
logging:
  level:
    uk.co.serin.thule: trace

# Thule configuration
thule:
  gatewayservice:
    healthcheck:
      services:
        - "thule-discovery-service"
        - "thule-configuration-service"
        - "thule-admin-service"
