version: "3.5"
services:
  ################################  Servers and Databases Required By Integration Tests  ################################
  mongo:
    image: mongo
    environment:
      TZ: Europe/London
    ports:
    - 27017:27017
    restart: always

