---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: thule-ingress
  namespace: thule
spec:
  rules:
  - host: piglet
    http:
      paths:
        - path: /thule-admin-service(/|$)(.*)
          backend:
            serviceName: thule-admin-service
            servicePort: 80
        - path: /thule-configuration-service(/|$)(.*)
          backend:
            serviceName: thule-configuration-service
            servicePort: 80
        - path: /thule-discovery-service(/|$)(.*)
          backend:
            serviceName: thule-discovery-service
            servicePort: 80
        - path: /thule-email-service(/|$)(.*)
          backend:
            serviceName: thule-email-service
            servicePort: 80
        - path: /thule-gateway-service(/|$)(.*)
          backend:
            serviceName: thule-gateway-service
            servicePort: 80
        - path: /thule-people-service(/|$)(.*)
          backend:
            serviceName: thule-people-service
            servicePort: 80
---
